<?php

namespace VOCS\PlatformBundle\Repository;

/**
 * WordTradUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordTradUserRepository extends \Doctrine\ORM\EntityRepository
{
}
